# Cerebro Secret Sniffing
# This tool finds secrets such as passwords, tokens, private keys and
# more in a Git repositories or list of Git repositories.

# Copyright (C) 2017 Twilio Inc.

# Cerebro is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version. Cerebro is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Cerebro; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

---
main:
  general:
    default_char_threshold: 6
    valid_hash_length: 30
    base64_chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
    hex_chars: '1234567890abcdefABCDEF'
  scan_targets: './config/targets.yaml'
  regexes_sought:
    - "\\s*([\\-]){5}begin\\s*[\\w]*\\s*private\\s*key" # Private Key Pattern
    - "[A-Za-z0-9]{30}" # Length of strings to match
    - "^(acqusition|apidev-coop|bzip|crypt|django-server|pwd|setup-tools|telnet|urlib3|urllib)$"
  regexes_ignored:
    - "^[A-Z]{2}[a-zA-Z0-9]+$"
  extensions_with_extra_checks:
    conf: 6
    yaml: 6
    yml: 6
    txt: 1
  excluded_extensions:
    - .png
    - .jpg
    - .jpeg
    - .gif
    - .storyboard
    - .xib
    - .lock
    - .md
  excluded_directories:
    - ".git"
    - "*test*"
    - "*Test*"
    - "*examples*"
    - "*jpgraph*"
    - "Zend*"
